
SELECT ca.CAR_ID,ca.CAR_TYPE,
ROUND(ca.DAILY_FEE*30*(100-pl.DISCOUNT_RATE)/100) AS FEE

from CAR_RENTAL_COMPANY_CAR ca join CAR_RENTAL_COMPANY_RENTAL_HISTORY hi
on  ca.CAR_ID = ca.CAR_ID
join CAR_RENTAL_COMPANY_DISCOUNT_PLAN pl
on ca.CAR_TYPE = pl.CAR_TYPE

WHERE ca.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE END_DATE > '2022-11-01' AND START_DATE < '2022-12-01'
) AND pl.DURATION_TYPE='30일 이상'
and  ca.CAR_TYPE IN ('세단', 'SUV')

group by ca.CAR_ID
having FEE>=500000 AND FEE<2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC